import Profile from "@/components/Profile";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
   title: "Blogs | Next 13 Example",
   description: "Users page generated by create next app",
};

const Page = () => {
   return (
      <div>
         Our Blogs
         <div className="mt-3">
            <ul className="w-96">
               <li className="w-full border-b-2 border-neutral-100 border-opacity-100 py-4 dark:border-opacity-50">
                  <Link href="/blogs/python-strings">Python Strings</Link>
               </li>
               <li className="w-full border-b-2 border-neutral-100 border-opacity-100 py-4 dark:border-opacity-50">
                  <Link href="/blogs/arrays-in-python">Arrays in Python</Link>
               </li>
               <li className="w-full border-b-2 border-neutral-100 border-opacity-100 py-4 dark:border-opacity-50">
                  <Link href="/blogs/python-control-statements">
                     Python Control Statements
                  </Link>
               </li>
            </ul>
         </div>
         <Profile />
      </div>
   );
};

export default Page;
