import { getRandomUserNoCache } from "@/actions/random.api";
import { Metadata } from "next";
import { useState } from "react";

export const metadata: Metadata = {
   title: "User | Next 13 Example",
   description: "Users page generated by create next app",
};

const Page = async () => {
   const user = await getRandomUserNoCache();

   if (!user) return <div>No user found!</div>;

   return (
      <div>
         <h4>
            Name {user.name.first} {user.name.last}
         </h4>
      </div>
   );
};

export default Page;
